services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Unlocalizedcrop\Command\MigrationCommand:
    tags:
      - name: 'console.command'
        command: 'unlocalizedcrop:migrate'
        schedulable: false
